### ISSUE TITLE
Using cyipopt without explicit Jacobian

### ISSUE THREAD

**Issue by m-clare** [matthias-k/cyipopt#16]
I'm working on a nonlinear optimization problem in which the calculation of the Jacobian is difficult to do. Is there a way to use a numerically found Jacobian in the class definition? Or must a Jacobian be explicitly created for the constraints?

I get a ValueError that:
Both the "constrains" and "jacobian" callbacks must be defined.

**Comment by moorepants** [comment]
IPOPT computes the Jacobian numerically if you don't provide it.

**Comment by moorepants** [comment]
There really isn't enough information here to debug this. I'm going to close the issue, but if you can reopen it if you provide a simple example that fails so that we can test things and see what the issue is.
