### ISSUE TITLE
Support PEP8 recommended function, method, and class formatted names

### ISSUE THREAD

**Issue by moorepants** [matthias-k/cyipopt#28]
For backward compatibility I'd like to dual support:

- `problem` -> `Problem`
- `problem.addOption()` -> `Problem.add_option()`
- `problem.setProblemScaling()` -> `Problem.set_problem_scaling()` or `Problem.set_scaling()`

So `ipopt/__init__.py` would have:

```python
from cyipopt import Problem
problem = Problem
```

And there would be dual methods:

```python
class Problem():
    def add_option(...):
        # all functional code here
    def addOption(self, *args, **kwargs):
        # maybe add a deprecation warning here
        self.add_option(*args, **kwargs)
```

**Comment by brocksam** [comment]
Is this still of interest? I'm keen to get involved and this issue looks like it'd be a good place to start.

**Comment by moorepants** [comment]
This is, the only thing is that we'd want to deprecate them method names, so have both for some time.

**Comment by brocksam** [comment]
> This is, the only thing is that we'd want to deprecate them method names, so have both for some time.

Yup, understood. Will follow your suggestion for dual support with deprecation warnings for the old non-PEP8 style.

**Comment by moorepants** [comment]
Cool, thanks for helping :)
