### ISSUE TITLE
'FunctionWithApproxJacobian' is not defined

### ISSUE THREAD

**Issue by jingxixu** [matthias-k/cyipopt#37]
I am trying to find a feasible solution to a set of non-linear inequality functions. I did it by passing a set of constraints and making the target function to always return constant. 

I call `minimize_ipopt` by 
```
minimize_ipopt(constant, x0, method="SLSQP", constraints=cons)
```

where `constant` is a function which always returns 1, x0 is just a random guess, and `cons` is a list of constraint dictionary just as `SciPy`. Then it shows the following error message:

```
NameError: name 'FunctionWithApproxJacobian' is not defined
```
 Could you please help me with debugging?

**Comment by tmfs10** [comment]
Same issue here https://github.com/matthias-k/cyipopt/issues/19

**Comment by moorepants** [comment]
Closing in favor of #19.
