### ISSUE TITLE
Fix pypi downloads

### ISSUE THREAD

**Issue by moorepants** [matthias-k/cyipopt#4]
The original maintainer of this package told me by email that he is no longer maintaining it. The pypi package (https://pypi.org/project/ipopt/) is now stale too. It'd be nice if this fork could take that over. Would you be willing to ask the owner of the pypi page to take it over?

**Comment by moorepants** [comment]
I think it might be even better to release this on PyPi as cyipopt instead of ipopt. This would help make the package name more unique.

**Comment by matthias-k** [comment]
This is a good idea. I probably will have time for this only somewhen in the next days since this would be my first PyPi release. Releasing it as `cyipopt` seems to be a more adequate name to me, too.

**Comment by moorepants** [comment]
I sent an email to the orginal author asking if he'd transfer the ipopt pypi name, but haven't heard back yet. But, yes I think naming it cyipopt is better.

**Comment by moorepants** [comment]
The original author said that he would give me access to the ipopt page on PyPi. So we could stick with that. Maybe it is a good idea to do for backwards compatibility reasons. But I am partial to having the package and main module be cyipopt so that a user would use `from cyipopt import *`.

**Comment by matthias-k** [comment]
I am also in favor of keeping the name cyipopt and rename the actual import name to be consistent, since these are not any official ipopt bindings.

**Comment by moorepants** [comment]
I've pushed 0.1.7/8/9 to PyPi. Going to close this. Will leave the name change to #14.
