### ISSUE TITLE
Add other installation procedures to Travis CI

### ISSUE THREAD

**Issue by moorepants** [matthias-k/cyipopt#40]
It would be useful to add manual installations to our CI build. Here are some options:

# Based on Ubuntu dependencies

1. Install all dependencies via APT.
2. Run `python setup.py build` to make sure it builds.

# Based on pip installed python dependencies

1. Install C dependencies via APT.
2. Install Python dependencies via ``pip install --user``.
3. Run `python setup.py build` to make sure it builds.

# With manually compiled IPOPT and Ubuntu deps

1. Install all ipopt and cyipopt dependencies via APT except IPOPT.
2. Download latest IPOPT source and compile into non-standard location.
3. Set `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH`.
4. Run `python setup.py build` to make sure it compiles.

# Manually compiled IPOPT with conda install deps

1. Install all ipopt and cyipopt dependencies via Anaconda/conda except IPOPT.
2. Download latest IPOPT source and compile into non-standard location.
3. Set `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH`.
4. Run `python setup.py build` to make sure it compiles.

**Comment by HuaweiWang** [comment]
I used the last approach several months ago and it was successful. Will add my installation steps tonight.

**Comment by HuaweiWang** [comment]
Sure, I will add it tonight.

**Comment by moorepants** [comment]
This is complete. Closing.
