### ISSUE TITLE
windows installation dll file not recognized

### ISSUE THREAD

**Issue by aschwele** [matthias-k/cyipopt#45]
We are trying to install cyipopt as a wrapper for ipopt on windows. Following the instructions, we modified the setup.py file accordingly and used Ipopt 3.9.2 since it was the only version with lib files at the link provided. 
However, when installing cyipopt through the setup.py file, we get the following error:
error: can't copy 'C:Users\...\Ipopt-3.9.2-win32-win64-dll\lib\x64\release\Ipopt39.dll': doesn't exist or not a regular file
any tips or solutions? where can we get functioning lib and dll files if that is the problem?

**Comment by moorepants** [comment]
We need some help with the Windows installation. There are multiple issues. If you can get it working, we'd love a pull request that fixes it, generalizes it, and gets it running on appveyor so it won't break again.

**Comment by aschwele** [comment]
Not sure how helpful we are going to be, since we are not expert developers. However, if you can provide us with functioning dll and lib files for ipopt we can try to dig a bit deeper, because we think this is our issue right now.

**Comment by moorepants** [comment]
I'd recommend contacting the ipopt developers for those. We don't develop ipopt.

**Comment by praveenhpc** [comment]
> We are trying to install cyipopt as a wrapper for ipopt on windows. Following the instructions, we modified the setup.py file accordingly and used Ipopt 3.9.2 since it was the only version with lib files at the link provided.
> However, when installing cyipopt through the setup.py file, we get the following error:
> error: can't copy 'C:Users...\Ipopt-3.9.2-win32-win64-dll\lib\x64\release\Ipopt39.dll': doesn't exist or not a regular file
> any tips or solutions? where can we get functioning lib and dll files if that is the problem?

I have the same issue and could fix it by using the escape character "\"  in the path 
ex:  IPOPT_LIB_DIRS = ['C:\/Users/xxxxx/xxxxx/xxxx]

**Comment by moorepants** [comment]
We have improved Windows support in #49 and #50 with confirmed builds. Please reopen this issue or a new one if you can't get things installed with the newer code.
