### ISSUE TITLE
Error when constraints=None

### ISSUE THREAD

**Issue by ThePaulrBear** [matthias-k/cyipopt#47]
There is a discrepancy between the behavior of minimize_ipopt and scipy.optimize.minimize when constraints=None. When that argument is passed to scipy.optimize.minimize, it runs find, but minimize_ipopt throws an error: `TypeError: 'NoneType' object is not iterable`

**Comment by moorepants** [comment]
This seems like an undocumented part of the scipy API. I do not see any mention of supporting `None` for the `constraints` keyword argument. See: https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize

I think it's best if we support the documented API, thus I'm going to close this.
