### ISSUE TITLE
ImportError: No module named Cython.Distutils

### ISSUE THREAD

**Issue by prashleo** [matthias-k/cyipopt#48]
Latest release ipopt 0.1.9  actualy doesn't reflect the setup.py in this repo.

install_requires parameter is not correctly set in the ipopt 0.1.9 .
please update it so that ipopt can be installed without user manually installing all the requirements

**Comment by moorepants** [comment]
@prashleo Can you please provide more information? We need to know what operating system you are using, what version of cipopt, what version of ipopt, the exact installation instructions you used, and the error message received. If you provide that we can likely help you.

**Comment by moorepants** [comment]
Closing due to no response.
