### ISSUE TITLE
how to speed up ?

### ISSUE THREAD

**Issue by argman** [matthias-k/cyipopt#61]
thanks for this repo, i'm using this to run a task, but each iteration takes more than 10 seconds, is there any way to speed up ?

**Comment by moorepants** [comment]
The only way you can speed up iterations is by making your objective, jacobian, and hessian evaulations faster. You should search the web for tips on profiling and speeding up your code. There are lots of ways to do so, from restructuring pure python code to using numpy, numba, cython, etc. We can't really offer that support here, but you can post to stackoverflow or the mailing lists for the libraries you are using.

**Comment by moorepants** [comment]
I'm closing this due to no response. Feel free to reopen if your issue is not solved.
