### ISSUE TITLE
Any plans to make it compatible with 3.13.XX IPOPT?

### ISSUE THREAD

**Issue by victoraalves** [matthias-k/cyipopt#62]
Firstly, I would like to thank you for this repo.

Secondly, as the title suggests, are there any plans to update this repo to make it compatible with the newest version of IPOPT? There is one pre-compiled by them 23 days ago: https://github.com/coin-or/Ipopt/releases/tag/releases%2F3.13.2

I've tried myself to install on Windows 10 using the folders lib and include from the newest compiled version (3.13.2), but failed:

![image](https://user-images.githubusercontent.com/50674829/82735817-ee2e7300-9cfa-11ea-90d9-846e648408ef.png)

After a quick inspection, I've found that the files from 3.11.0 (the recommended version by you) and the 3.13.2 are not the same, maybe that is the reason.

3.11.0 runs great. But it would be nice to have the newest (and probably with a lot of bugfixes) code.

Thank you once again for this amazing repo!

**Comment by moorepants** [comment]
We'd love this to compile on windows for a selection of IPOPT versions. If you have the know how, we'd welcome any pull requests.

**Comment by apommel** [comment]
According to IPOPT changelog (see https://coin-or.github.io/Ipopt/CHANGELOG.html), 3.13.0 broke backward compatibility on some points. Has anyone checked that cyipopt works properly on Linux with the latest builds, before attempting to tackle that on Windows?

**Comment by moorepants** [comment]
No, nothing has been done regarding 3.13.0.

**Comment by apommel** [comment]
I tried cyipopt with a custom compiled Ipopt 3.13.2 on Ubuntu through WSL2, and all of the tests execute correctly. However, because the directory organization of Ipopt has changed quite a bit, the instructions are not up to date.

**Comment by apommel** [comment]
I managed to make it work on Windows too. However, it breaks compatibility with pre-3.13.0 Ipopt as it does not seem that there is a simple way to detect Ipopt version automatically. Otherwise it would be possible to use an environment variable for Ipopt version too.
However I think supporting only Ipopt>=3.13.0 would also be acceptable as the build process has been vastly improved, the directory structure seems to be quite definitive this time, and they seem to be motivated to provide DLL files for Windows at each release.

**Comment by moorepants** [comment]
Maybe I should release a version of cyipopt that works for less than 3.13.0 first. Then we can make the subsequent release be >= 3.13.0.

**Comment by victoraalves** [comment]
examplehs071.py went smoothly (Windows 10):

![image](https://user-images.githubusercontent.com/50674829/83667815-5f94de00-a5a5-11ea-8a29-729196cf2b73.png)


![image](https://user-images.githubusercontent.com/50674829/83667588-062caf00-a5a5-11ea-9009-635207f2d993.png)

**Comment by victoraalves** [comment]
I had to also add the "bin" folder (from the latest IpOpt build (3.13.2)) to the cyipopt root folder before running "setup.py". Maybe this is the directory organization that @apommel is referring to?

**Comment by apommel** [comment]
@victoraalves Yes among other things. I did not specify it as I had expected people to extract the entire Ipopt directory in the cyipopt folder. I will make sure to detail that in the documentation once everything is finalized though.

**Comment by moorepants** [comment]
Version 0.2.0 support 3.13 series on Windows. Update to test.
