### ISSUE TITLE
Gradient Estimation with Finite-difference?

### ISSUE THREAD

**Issue by ShihaoWang** [matthias-k/cyipopt#68]
I am currently solving a nonlinear programming problem where it is pretty difficult for me to provide explicitly gradient or jacobian matrix. I think that IPOPT should have this option to enable a finite-difference method for gradient estimation. However, I am not sure how to set this option within cyipopt wrapper. Can you provide me with some instructions?

Thanks,

**Comment by moorepants** [comment]
ipopt can compute finite differences, as far as I can remember. But cyipopt may not have that option. I noticed this error:

https://github.com/matthias-k/cyipopt/blob/master/src/cyipopt.pyx#L303

that says a jacobian has to be defined.

You may want to look at the ipopt options and see if there is an option you can enable to set it to do finite differences. But it is possible cyipopt doesn't support that.

If it doesn't then someone would need to edit the problem class to support providing no jacobian.

**Comment by moorepants** [comment]
What you can do is define functions that take the finite differences your self. For example, you can maybe use numpy's gradient function.

**Comment by ShihaoWang** [comment]
Thanks for your reply. It seems that Ipopt's built-in finite-difference method can be enabled with 
>     nlp.addOption('jacobian_approximation', 'finite-difference-values')
>     nlp.addOption('hessian_approximation', 'limited-memory')
These two options are supported in cyipopt wrapper and I think that in this case, the optimization problem can be solved without user-defined gradient or jacobian.

**Comment by ShihaoWang** [comment]
To be more specific, instead of directly minimizing the original objective, this problem can be reformulated with introducing a new slack variable where an equality constraint is added to make this slack variable equals to the original objective and the new objective is to minimize this slack variable. In this case, the gradient function is pretty straightforward and the problem is solvable.

**Comment by moorepants** [comment]
Ok, we'd welcome having this example added to the documentation if you'd like to contribute. I'm going to close this issue as solved.
