### ISSUE TITLE
Problem in the tutorial

### ISSUE THREAD

**Issue by hfhc2** [matthias-k/cyipopt#77]
I noticed a problem in the [tutorial](https://pythonhosted.org/ipopt/tutorial.html), notably the sample code:

    def hessianstructure(self):
        #
        # The structure of the Hessian
        # Note:
        # The default hessian structure is of a lower triangular matrix. Therefore
        # this function is redundant. I include it as an example for structure
        # callback.
        #
        global hs

        hs = sps.coo_matrix(np.tril(np.ones((4, 4))))
        return (hs.col, hs.row)

This makes it sound as though the tuple to be returned is of the form `(column_indices, row_indices)`, although it *should*
be the other way around, i.e., `(row_indices, column_indices)`. This is inconsequential in the example, since the indices are identical, but it really matters in case of the structure of a sparse non-rectangular Jacobian.

**Comment by brocksam** [comment]
Addressed in https://github.com/matthias-k/cyipopt/pull/75/commits/fb1931633a4afb91000f092598d108e7db8ee0de as part of PR #75.
