### ISSUE TITLE
Suppressing documentation output in the first run

### ISSUE THREAD

**Issue by Nikronic** [matthias-k/cyipopt#80]
Hi,
Whenever you initialize Ipopt, it prints following:
```
******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************
```

As the the person who posted the question in the following thread mentioned it, I am using Ipopt in a loop so this print line could be annoying in combination with other info.

I found this issue is being addressed here by a temp solution, but I do not know how to do it in Python.
https://list.coin-or.org/pipermail/ipopt/2013-September/003510.html

I wonder is there any workaround for this problem?

Bests

**Comment by Nikronic** [comment]
Sorry for inconvenience and not diving deeper,

Solution: https://groups.google.com/g/julia-opt/c/TVmuXFWfeBM/m/DxIP2bWFEAAJ

in summary (for Python):
```
nlp.addOption('sb', 'yes')
```

Although, I cannot find `sb` option in official docs.

**Comment by moorepants** [comment]
Yes, it is undocumented for some reason...
