### ISSUE TITLE
docker, vagrant, Makefile

### ISSUE THREAD

**Issue by moorepants** [matthias-k/cyipopt#83]
The docker & vagrant directories are not maintained and neither is the old Makefile that is specific to the original author's computer. I think we should remove these unless someone wants to maintain them.

**Comment by brocksam** [comment]
I'm in favour of removing these.

**Comment by brocksam** [comment]
Addressed in https://github.com/matthias-k/cyipopt/pull/75/commits/794d20e1db37036d58089089e89cf6b0198e6518 as part of PR #75.
